---
development:
  cloud_name: dewcnjcxg
  api_key: '792474641426442'
  api_secret: cBOhGuTXEYAvlEiitzEXpOXjjXg
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dewcnjcxg
  api_key: '792474641426442'
  api_secret: cBOhGuTXEYAvlEiitzEXpOXjjXg
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dewcnjcxg
  api_key: '792474641426442'
  api_secret: cBOhGuTXEYAvlEiitzEXpOXjjXg
  enhance_image_tag: true
  static_file_support: false
